[tool.mypy]
plugins = ["mypy_django_plugin.main"]

[tool.django-stubs]
django_settings_module = "myproject.settings"

[tool.isort]
profile = "black"
multi_line_output = 3
lines_after_imports = 2
lines_between_sections = 0
